// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ChangeBattleMode","status":true,"description":"Allows side view and front view battles in the same game","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}}
];
